server:
  port: 8030

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    virtual-host: /test

 ####################################  ACK反馈配置
    listener:
      simple:
        retry:
          enabled: true    #开启重试
    template:
      retry:
        max-attempts: 5   #重试次数，默认为3次
